Repository bridgecrewio/checkov, pull requests merged in 2021-11, with the labels that each got.

#1880 [AUTO-PR] Update pipenv packages
  Pipfile.lock
Labels: automated pr

#1907 Add checks for NGINX Ingress CVE-2021-25742
  checkov/kubernetes/checks/NginxIngressCVE202125742Alias.py
  checkov/kubernetes/checks/NginxIngressCVE202125742AllSnippets.py
  checkov/kubernetes/checks/NginxIngressCVE202125742Lua.py
  tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation1-FAILED.yaml
  tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation2-nollua-PASSESONEFAILSONE.yaml
  tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation3-alias.yaml
  tests/kubernetes/checks/example_NginxIngressCVE202125742/noannotations-PASSED.yaml
  tests/kubernetes/checks/test_NginxIngressCVE202125742Alias.py
  tests/kubernetes/checks/test_NginxIngressCVE202125742AllSnippets.py
  tests/kubernetes/checks/test_NginxIngressCVE202125742Lua.py
Labels: check

#1916 [AUTO-PR] Update pipenv packages
  Pipfile.lock
Labels: automated pr

#1991 Updated HELM documentation
  docs/4.Integrations/Helm.md
Labels: documentation

#2007 [AUTO-PR] Update pipenv packages
  Pipfile.lock
Labels: automated pr
